function(target_cxx23 TARGET)
    set_property(TARGET ${TARGET} PROPERTY CXX_STANDARD 23)
    set_property(TARGET ${TARGET} PROPERTY CXX_STANDARD_REQUIRED ON)
    set_property(TARGET ${TARGET} PROPERTY CXX_EXTENSIONS OFF)
endfunction()
